obj-$(CONFIG_CAPEBUS_BONE_GENERIC)	+= bone-generic-cape.o
obj-$(CONFIG_CAPEBUS_BONE_GEIGER)	+= bone-geiger-cape.o
obj-$(CONFIG_CAPEBUS_BONE_NIXIE)	+= bone-nixie-cape.o
obj-$(CONFIG_CAPEBUS_SPI_VFD)		+= bone-spi-vfd.o
